apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shiori
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pipol31/shiori
    path: chart/shiori
  destination:
    server: "https://kubernetes.default.svc"
    namespace: shiori
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
